app = "demo-pinball-friends"
primary_region = "cdg"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[processes]
  app = ""
  # Fly is automatically configured to run laravel scheduler
  cron = "cron -f"

[env]
  APP_ENV = "demo"
  APP_NAME="Demo Pinball Friends"
  APP_URL="https://demo.pinball-friends.com"
  APP_LOCALE="en"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/my_demo_database_volume/db.sqlite"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[[mounts]]
  source = "my_demo_database_volume"
  destination = "/var/www/html/my_demo_database_volume"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
